-- 코드를 작성해주세요
select count(B.FISH_NAME) as FISH_COUNT
-- A.ID, A.FISH_TYPE, B.FISH_NAME, A.LENGTH, A.TIME
from FISH_INFO A
left join FISH_NAME_INFO B
on A.FISH_TYPE = B.FISH_TYPE
WHERE B.FISH_NAME = 'BASS' or B.FISH_NAME = 'SNAPPER';